# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: WinCert"
kfutil store-types create WinCert

Write-Host "Creating store type: IISU"
kfutil store-types create IISU

Write-Host "Creating store type: WinSql"
kfutil store-types create WinSql

Write-Host "Creating store type: WinAdfs"
kfutil store-types create WinAdfs

