# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: WinCert"
$Body = @'
{
  "Name": "Windows Certificate",
  "ShortName": "WinCert",
  "Capability": "WinCert",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true,
      "Description": "Multiple choice value specifying which protocol to use.  Protocols https or http use WinRM to connect from Windows to Windows Servers.  Using ssh is only supported when running the orchestrator in a Linux environment."
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true,
      "Description": "String value specifying the port number that the Windows target server's WinRM listener is configured to use. Example: '5986' for HTTPS or '5985' for HTTP.  By default, when using ssh in a Linux environment, the default port number is 22."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Username used to log into the target server for establishing the WinRM session. Example: 'administrator' or 'domain\\username'.  (This field is automatically created)"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Password corresponding to the Server Username used to log into the target server.  When establishing a SSH session from a Linux environment, the password must include the full SSH Private key. (This field is automatically created)"
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "Description": "Determine whether the server uses SSL or not (This field is automatically created)"
    },
    {
      "Name": "JEAEndpointName",
      "DisplayName": "JEA End Point Name",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Name of the JEA endpoint to use for the session (This field is automatically created)"
    }
  ],
  "EntryParameters": [
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: IISU"
$Body = @'
{
  "Name": "IIS Bound Certificate",
  "ShortName": "IISU",
  "Capability": "IISU",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true,
      "Description": "Multiple choice value specifying which protocol to use.  Protocols https or http use WinRM to connect from Windows to Windows Servers.  Using ssh is only supported when running the orchestrator in a Linux environment."
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true,
      "Description": "String value specifying the port number that the Windows target server's WinRM listener is configured to use. Example: '5986' for HTTPS or '5985' for HTTP.  By default, when using ssh in a Linux environment, the default port number is 22."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Username used to log into the target server for establishing the WinRM session. Example: 'administrator' or 'domain\\username'. (This field is automatically created)"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Password corresponding to the Server Username used to log into the target server.  When establishing a SSH session from a Linux environment, the password must include the full SSH Private key. (This field is automatically created)"
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "Description": "Determine whether the server uses SSL or not (This field is automatically created)"
    },
    {
      "Name": "JEAEndpointName",
      "DisplayName": "JEA End Point Name",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Name of the JEA endpoint to use for the session (This field is automatically created)"
    }
  ],
  "EntryParameters": [
    {
      "Name": "Port",
      "DisplayName": "Port",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "443",
      "Options": "",
      "Description": "String value specifying the IP port to bind the certificate to for the IIS site. Example: '443' for HTTPS."
    },
    {
      "Name": "IPAddress",
      "DisplayName": "IP Address",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": true,
        "OnReenrollment": true
      },
      "DependsOn": "",
      "DefaultValue": "*",
      "Options": "",
      "Description": "String value specifying the IP address to bind the certificate to for the IIS site. Example: '*' for all IP addresses or '192.168.1.1' for a specific IP address."
    },
    {
      "Name": "HostName",
      "DisplayName": "Host Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "String value specifying the host name (host header) to bind the certificate to for the IIS site. Leave blank for all host names or enter a specific hostname such as 'www.example.com'."
    },
    {
      "Name": "SiteName",
      "DisplayName": "IIS Site Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": true,
        "OnReenrollment": true
      },
      "DependsOn": "",
      "DefaultValue": "Default Web Site",
      "Options": "",
      "Description": "String value specifying the name of the IIS web site to bind the certificate to. Example: 'Default Web Site' or any custom site name such as 'MyWebsite'."
    },
    {
      "Name": "SniFlag",
      "DisplayName": "SSL Flags",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "0",
      "Options": "",
      "Description": "A 128-Bit Flag that determines what type of SSL settings you wish to use.  The default is 0, meaning No SNI.  For more information, check IIS documentation for the appropriate bit setting.)"
    },
    {
      "Name": "Protocol",
      "DisplayName": "Protocol",
      "Type": "MultipleChoice",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": true,
        "OnReenrollment": true
      },
      "DependsOn": "",
      "DefaultValue": "https",
      "Options": "https,http",
      "Description": "Multiple choice value specifying the protocol to bind to. Example: 'https' for secure communication."
    },
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "[\"My\",\"WebHosting\"]",
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: WinSql"
$Body = @'
{
  "Name": "WinSql",
  "ShortName": "WinSql",
  "Capability": "WinSql",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true,
      "Description": "Multiple choice value specifying which protocol to use.  Protocols https or http use WinRM to connect from Windows to Windows Servers.  Using ssh is only supported when running the orchestrator in a Linux environment."
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true,
      "Description": "String value specifying the port number that the Windows target server's WinRM listener is configured to use. Example: '5986' for HTTPS or '5985' for HTTP.  By default, when using ssh in a Linux environment, the default port number is 22."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Username used to log into the target server for establishing the WinRM session. Example: 'administrator' or 'domain\\username'. (This field is automatically created)"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Password corresponding to the Server Username used to log into the target server.  When establishing a SSH session from a Linux environment, the password must include the full SSH Private key. (This field is automatically created)"
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "Description": "Determine whether the server uses SSL or not (This field is automatically created)"
    },
    {
      "Name": "RestartService",
      "DisplayName": "Restart SQL Service After Cert Installed",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true,
      "Description": "Boolean value (true or false) indicating whether to restart the SQL Server service after installing the certificate. Example: 'true' to enable service restart after installation."
    },
    {
      "Name": "JEAEndpointName",
      "DisplayName": "JEA End Point Name",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Name of the JEA endpoint to use for the session (This field is automatically created)"
    }
  ],
  "EntryParameters": [
    {
      "Name": "InstanceName",
      "DisplayName": "Instance Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "String value specifying the SQL Server instance name to bind the certificate to. Example: 'MSSQLServer' for the default instance or 'Instance1' for a named instance."
    },
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "My",
  "PrivateKeyAllowed": "Optional",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: WinAdfs"
$Body = @'
{
  "Name": "ADFS Rotation Manager",
  "ShortName": "WinAdfs",
  "Capability": "WinAdfs",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true,
      "Description": "Multiple choice value specifying which protocol to use.  Protocols https or http use WinRM to connect from Windows to Windows Servers.  Using ssh is only supported when running the orchestrator in a Linux environment."
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true,
      "Description": "String value specifying the port number that the Windows target server's WinRM listener is configured to use. Example: '5986' for HTTPS or '5985' for HTTP.  By default, when using ssh in a Linux environment, the default port number is 22."
    },
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Username used to log into the target server for establishing the WinRM session. Example: 'administrator' or 'domain\\username'. (This field is automatically created)"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "Password corresponding to the Server Username used to log into the target server.  When establishing a SSH session from a Linux environment, the password must include the full SSH Private key. (This field is automatically created)"
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true,
      "Description": "Determine whether the server uses SSL or not (This field is automatically created)"
    }
  ],
  "EntryParameters": [
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "My",
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

