name: Keyfactor Merge Cert Store Types
on: [workflow_dispatch]

jobs:
  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      update_catalog: ${{ steps.read-json.outputs.update_catalog }}
      integration_type:  ${{ steps.read-json.outputs.integration_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Store json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          $myvar = $json.update_catalog
          echo "update_catalog=$myvar" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          $myvar = $json.integration_type
          echo "integration_type=$myvar" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

  call-update-store-types-workflow:
    needs: get-manifest-properties
    if: needs.get-manifest-properties.outputs.integration_type == 'orchestrator' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: Keyfactor/actions/.github/workflows/update-store-types.yml@main
    secrets: 
      token: ${{ secrets.UPDATE_STORE_TYPES }}
