name: Keyfactor Bootstrap Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize, edited, reopened]
  push:
  create:
    branches:
      - 'release-*.*'

jobs:
  call-starter-workflow:
    uses: keyfactor/actions/.github/workflows/starter.yml@v4
    with:
      command_token_url: ${{ vars.COMMAND_TOKEN_URL }} # Only required for doctool generated screenshots
      command_hostname: ${{ vars.COMMAND_HOSTNAME }} # Only required for doctool generated screenshots
      command_base_api_path: ${{ vars.COMMAND_API_PATH }} # Only required for doctool generated screenshots
    secrets:
      token: ${{ secrets.V2BUILDTOKEN}} # REQUIRED
      gpg_key: ${{ secrets.KF_GPG_PRIVATE_KEY }} # Only required for golang builds
      gpg_pass: ${{ secrets.KF_GPG_PASSPHRASE }} # Only required for golang builds
      scan_token: ${{ secrets.SAST_TOKEN }} # REQUIRED
      entra_username: ${{ secrets.DOCTOOL_ENTRA_USERNAME }} # Only required for doctool generated screenshots
      entra_password: ${{ secrets.DOCTOOL_ENTRA_PASSWD }} # Only required for doctool generated screenshots
      command_client_id: ${{ secrets.COMMAND_CLIENT_ID }} # Only required for doctool generated screenshots
      command_client_secret: ${{ secrets.COMMAND_CLIENT_SECRET }} # Only required for doctool generated screenshots
