#!/usr/bin/env bash

# Creates all 4 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# WinCert — Hostname of the Windows Server containing the certificate store to be managed. If this value is a hostname, a WinRM session will be established using the credentials specified in the Server Username and Server Password fields. For more information, see [Client Machine](#note-regarding-client-machine).
# ---------------------------------------------------------------------------
create_store_type "WinCert" '{
  "Name": "Windows Certificate",
  "ShortName": "WinCert",
  "Capability": "WinCert",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": [
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "",
  "PrivateKeyAllowed": "Optional",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "StorePathDescription": "Windows certificate store path to manage. The store must exist in the Local Machine store on the target server, e.g., 'My' for the Personal Store or 'Root' for the Trusted Root Certification Authorities Store."
}'

# ---------------------------------------------------------------------------
# IISU — Hostname of the Windows Server containing the IIS certificate store to be managed. If this value is a hostname, a WinRM session will be established using the credentials specified in the Server Username and Server Password fields.  For more information, see [Client Machine](#note-regarding-client-machine).
# ---------------------------------------------------------------------------
create_store_type "IISU" '{
  "Name": "IIS Bound Certificate",
  "ShortName": "IISU",
  "Capability": "IISU",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": [
    {
      "Name": "Port",
      "DisplayName": "Port",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "443",
      "Options": "",
      "Description": "String value specifying the IP port to bind the certificate to for the IIS site. Example: '443' for HTTPS."
    },
    {
      "Name": "IPAddress",
      "DisplayName": "IP Address",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": true,
        "OnReenrollment": true
      },
      "DependsOn": "",
      "DefaultValue": "*",
      "Options": "",
      "Description": "String value specifying the IP address to bind the certificate to for the IIS site. Example: '*' for all IP addresses or '192.168.1.1' for a specific IP address."
    },
    {
      "Name": "HostName",
      "DisplayName": "Host Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "String value specifying the host name (host header) to bind the certificate to for the IIS site. Leave blank for all host names or enter a specific hostname such as 'www.example.com'."
    },
    {
      "Name": "SiteName",
      "DisplayName": "IIS Site Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": true,
        "OnReenrollment": true
      },
      "DependsOn": "",
      "DefaultValue": "Default Web Site",
      "Options": "",
      "Description": "String value specifying the name of the IIS web site to bind the certificate to. Example: 'Default Web Site' or any custom site name such as 'MyWebsite'."
    },
    {
      "Name": "SniFlag",
      "DisplayName": "SSL Flags",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "0",
      "Options": "",
      "Description": "A 128-Bit Flag that determines what type of SSL settings you wish to use.  The default is 0, meaning No SNI.  For more information, check IIS documentation for the appropriate bit setting.)"
    },
    {
      "Name": "Protocol",
      "DisplayName": "Protocol",
      "Type": "MultipleChoice",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": true,
        "OnRemove": true,
        "OnReenrollment": true
      },
      "DependsOn": "",
      "DefaultValue": "https",
      "Options": "https,http",
      "Description": "Multiple choice value specifying the protocol to bind to. Example: 'https' for secure communication."
    },
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "[\"My\",\"WebHosting\"]",
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "StorePathDescription": "Windows certificate store path to manage. Choose 'My' for the Personal store or 'WebHosting' for the Web Hosting store."
}'

# ---------------------------------------------------------------------------
# WinSql — Hostname of the Windows Server containing the SQL Server Certificate Store to be managed. If this value is a hostname, a WinRM session will be established using the credentials specified in the Server Username and Server Password fields. For more information, see [Client Machine](#note-regarding-client-machine).
# ---------------------------------------------------------------------------
create_store_type "WinSql" '{
  "Name": "WinSql",
  "ShortName": "WinSql",
  "Capability": "WinSql",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    },
    {
      "Name": "RestartService",
      "DisplayName": "Restart SQL Service After Cert Installed",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    }
  ],
  "EntryParameters": [
    {
      "Name": "InstanceName",
      "DisplayName": "Instance Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "String value specifying the SQL Server instance name to bind the certificate to. Example: 'MSSQLServer' for the default instance or 'Instance1' for a named instance."
    },
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "My",
  "PrivateKeyAllowed": "Optional",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Forbidden",
  "StorePathDescription": "Fixed string value 'My' indicating the Personal store on the Local Machine. This denotes the Windows certificate store to be managed for SQL Server."
}'

# ---------------------------------------------------------------------------
# WinAdfs — Since this extension type must run as an agent (The UO Must be installed on the PRIMARY ADFS Server), the ClientMachine must follow the naming convention as outlined in the Client Machine Instructions. Secondary ADFS Nodes will be automatically be updated with the same certificate added on the PRIMARY ADFS server.
# ---------------------------------------------------------------------------
create_store_type "WinAdfs" '{
  "Name": "ADFS Rotation Manager",
  "ShortName": "WinAdfs",
  "Capability": "WinAdfs",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "spnwithport",
      "DisplayName": "SPN With Port",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "WinRM Protocol",
      "DisplayName": "WinRM Protocol",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "https,http,ssh",
      "Required": true
    },
    {
      "Name": "WinRM Port",
      "DisplayName": "WinRM Port",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "5986",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": [
    {
      "Name": "ProviderName",
      "DisplayName": "Crypto Provider Name",
      "Type": "String",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "DependsOn": "",
      "DefaultValue": "",
      "Options": "",
      "Description": "Name of the Windows cryptographic service provider to use when generating and storing private keys. For more information, refer to the section 'Using Crypto Service Providers'"
    }
  ],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathValue": "My",
  "PrivateKeyAllowed": "Required",
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": true,
  "CustomAliasAllowed": "Forbidden",
  "StorePathDescription": "Fixed string value of 'My' indicating the Personal store on the Local Machine. All ADFS Service-Communications certificates are located in the 'My' personal store by default."
}'


echo "Completed."
