#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: WinCert"
kfutil store-types create WinCert

echo "Creating store type: IISU"
kfutil store-types create IISU

echo "Creating store type: WinSql"
kfutil store-types create WinSql

echo "Creating store type: WinAdfs"
kfutil store-types create WinAdfs

